services:
  - type: web
    name: fees
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
